java-web/src/main/java/pervuy/entity/UserLogin.java
package pervuy.entity;

import pervuy.libs.EX;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class UserLogin extends User{

    private LocalDateTime lastLogin;
    public UserLogin(User user, LocalDateTime lastLogin){
        super(user.getLogin(),user.getPassword(),user.getProfession(),user.id(),user.getPathPhoto());
        this.lastLogin = lastLogin;
    }

    public String getLastLogin() {

        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("d/MM/yyyy");
        return lastLogin.format(dateTimeFormatter);

    }

    public String getDaysAgo() {
        throw EX.NI;
        //return "1 days ago";
    }
}

java-web/src/main/java/pervuy/servlets/LoginServlet.java
package pervuy.servlets;

import freemarker.template.Configuration;
import freemarker.template.TemplateException;
import lombok.SneakyThrows;
import pervuy.entity.User;
import pervuy.service.UserService;

import javax.servlet.ServletException;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;

public class LoginServlet extends HttpServlet {

    private final UserService userService;

    // http://localhost:8080/login
    @SneakyThrows
    public LoginServlet() {
        this.userService = new UserService();
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {

        Configuration configuration = TinderConfiguration.of("templates");

        HashMap<String, Object> dataModel = new HashMap<>();

        try (PrintWriter printWriter = resp.getWriter()){
            configuration
                    .getTemplate("login.ftl")
                    .process(dataModel, printWriter);
        } catch (TemplateException e) {
            throw new RuntimeException(e);
        }
    }

    @SneakyThrows
    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {

        String password = req.getParameter("password");
        User userByLogin = userService.getUserByLogin(req.getParameter("email")).orElse(null);
        if (userByLogin == null){
            resp.sendRedirect("login");
        }else {
            if (userByLogin.getPassword().equals(password)) {
                userService.insertUserLoginHistory(userByLogin);
                resp.addCookie(new Cookie("UUID", userByLogin.id().toString()));
                resp.sendRedirect("/users");
            }
        }


    }
}

java-web/src/main/java/pervuy/servlets/RegisterServlet.java
package pervuy.servlets;

import freemarker.template.Configuration;
import freemarker.template.TemplateException;
import lombok.SneakyThrows;
import pervuy.entity.User;
import pervuy.service.UserService;

import javax.servlet.ServletException;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.UUID;

public class RegisterServlet extends HttpServlet {

    private final UserService userService;

    @SneakyThrows
    public RegisterServlet() {
        this.userService = new UserService();
    }

    // http://localhost:8080/register
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {

        Configuration configuration = TinderConfiguration.of("templates");

        HashMap<String, Object> dataModel = new HashMap<>();

        try (PrintWriter printWriter = resp.getWriter()){
            configuration
                    .getTemplate("register.ftl")
                    .process(dataModel, printWriter);
        } catch (TemplateException e) {
            throw new RuntimeException(e);
        }
    }

    @SneakyThrows
    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp){

        String password = req.getParameter("password");
        String email = req.getParameter("email");
        User userByLogin = userService.getUserByLogin(email).orElse(null);
        if (userByLogin != null){
            resp.sendRedirect("register");
        }else {
            UUID refUser = UUID.randomUUID();
            User user = new User(email, password, "", refUser, "");

            userService.saveUser(user);
            userService.insertUserLoginHistory(user);

            resp.addCookie(new Cookie("UUID", refUser.toString()));
            resp.sendRedirect("/users");
        }
    }
}

java-web/src/main/resources/templates/login.ftl
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="img/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="css/style.css">
</head>

<body class="text-center">
    <form class="form-signin" method="post">
        <img class="mb-4" src="https://getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" name = "email" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" name = "password" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; Tinder 2018</p>
    </form>
</body>
</html>

java-web/src/main/resources/templates/people-list.ftl
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="img/favicon.ico">

    <title>People list</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <!-- Bootstrap core CSS -->
     <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
     <link rel="stylesheet" href="css/style.css">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-8 offset-2">
            <div class="panel panel-default user_panel">
                <div class="panel-heading">
                    <h3 class="panel-title">User List</h3>
                </div>
                <div class="panel-body">
                    <div class="table-container">
                        <table class="table-users table" border="0">
                            <#list users>
                            <tbody>
                                <#items as item>
                                <tr>
                                    <td width="10">
                                        <div class="avatar-img">
                                            <!-- <img class="img-circle" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxhcCYW4QDWMOjOuUTxOd50KcJvK-rop9qE9zRltSbVS_bO-cfWA" />-->
                                            <img class="img-circle" src=${item.pathPhoto}>
                                        </div>

                                    </td>
                                    <td class="align-middle">
                                        ${item.login}
                                    </td>
                                    <td class="align-middle">
                                        ${item.profession}
                                    </td>
                                    <td  class="align-middle">
                                        Last Login: ${item.lastLogin}<br><small class="text-muted">${item.daysAgo}</small>
                                    </td>
                                </tr>
                                </#items>
                            </tbody>
                            </#list>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

java-web/src/main/resources/templates/register.ftl
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="img/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="css/style.css">
</head>

<body class="text-center">
    <form class="form-signin" method="post">
        <img class="mb-4" src="https://getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Please registrations</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" name = "email" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" name = "password" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Registrations</button>
        <p class="mt-5 mb-3 text-muted">&copy; Tinder 2018</p>
    </form>
</body>
</html>